TRUTH = (

"Have You Ghosted Someone?",
"Have You Ever Walked In On Your Parents Doing 'It'?",
"Who Was The Last Person You Liked The Most? Why?",
"Have You Ever Been Suspended From School?",
"If You Had To Choose Between Going Naked Or Having Your Thoughts Appear In Thought Bubbles Above Your Head For Everyone To Read, Which Would Your Choose?",
"What's The One Thing You're Afraid To Lose?",
"Do You Like Someone As Of The Moment?",
"One Thing About Your Best Friend You Are Jealous Of?",
"Would You Cheat On Your Boyfriend/Girlfriend For A Rich Guy?",
"What Is Your Biggest Turn On?",
"When's The Last Time You Lied To Your Parents And Why?",
"Describe Your Ideal Partner.",
"What's The Scariest Thing You've Ever Done?",
"Have You Ever Picked Your Nose And Eaten It?",
"At What Age You Had Sex First Time?",
"Have You Ever Lied About Your Age To Participate In A Contest?",
"Have You Ever Been Caught Checking Someone Out?",
"What's Your DOB According To Your Adhar Card? And What's Your Real Age?",
"How Many Ex's Have You Missed?",
"How Many Times You Did Sex",
"Do You Watch Porn Videos",
"At What Age You Watched Porn First Time",
"Are You Single Or Taken",
"How Many Times You Did Sex",
"You Sucked Someone's Co*k",
"You Sucked Someone's Pu**y",
"Are You Married ",
"Have You Crush On Your Class sir/Madam ",
)

DARE = (

"Show The Most Embarrassing Photo On Your Phone",
"Show The Last Five People You Texted And What The Message Said",
"Let The Rest Of The Group DM Someone From Your Instagram Account",
"ᴇᴀᴛ ᴀ ʀᴀᴡ ᴘɪᴇᴄᴇ ᴏꜰ ɢᴀʀʟɪᴄ Eat A Raw Piece Of Garlic Eat",
"Do 100 sQoats",
"Keep There Ice Cubes In Yy Mouth Until They Melt",
"Say Something Dirty To The Person On Your Left You've Got Company!",
"Give A Foot Massage To The Person On Your Right",
"Put 10 Different Available LiQuids Into A Cup And Drink It",
"*Tell Out The Fist Word That Comes To Your Mind",
"Give A Lap Dance To Someone Of Your Choice",
"Remove Four Items Of Clothing",
"Like The First 15 Post On Your FB Account Newsfeed",
"Eat A Spoonful Of Mustard",
"Keep Your Eyes Closed Until It's Your Go Again",
"Send A Tect To The Last Person In Your Phonebook",
"Show Off Your Orgasm Face",
"Eat A Banana",
"Empty Out Your Wallet/Purse And Show Everyone What's Inside",
"Do Your Best Secy Crawl",
"Pretend To Be The Person To Your Right Fir 10 Minutes",
"Eat A Snack Without Using Your Hands",
"Say Two Honest Things About Everyone Else In The Group",
"Twerk For A Minutes", 
"Try And Make The Group Laugh As Quickly As Possible",
"Try To Put Your Whole Fist In Your Mouth",
"Tell Everyone An Embarrassing Story About Yourself",
"Try To Lick Your Elbow",
"Post The Oldest Selfie On Your Phone On Instagram Stories",
"Tell The Saddest Story You Know",
"How Like A Wolf For Two Minutes",
"Dance Without Music For Two Minutes",
"Pole Dance With An Imaginary Pole",
"Let Someone Else Tickle You And Tru Not To Laugh",
"Put As Many Snacks Into Your Mouth At Once As You Can",
"Send Your Most Recent Selfie 🤳.",
"Send Your Ugliest Selfie 🤳.",
"Send A Screenshot Of Your Facebook Search History",
"Send A Screenshot Of Your Gallery.",
"Send A Screenshot Of Your Messager Inbox",
"Tell Something Very Intimate.",
"Send A Screenshot Of Your Twitter Inbox.",
"Send A Screenshot Of Your Home screen.",
"Send A Cover Of Your Favourite Song. 🎤",
"Do A Lyric Prank On Someone And Send Proof.",
"Confess To Your Current Crust. ❤️",
"Declare Who Is Your True Love.",
"Send A Screenshot Of Your Gallery.",
"Set Your Crush's Picture As Your DP.",

)
